#.travis.yml
dist: trusty
sudo: required
language: node_js

node_js:
  - 10.15.3

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "wlucha"
    token:
      secure: 4e257070ac37457593f55864bbdb6de556d32d8a"


install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
  - sonar-scanner
