#.travis.yml
dist: trusty
sudo: required
language: node_js

node_js:
  - 10.15.3

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "wlucha"
    token:
      secure: $SONAR_TOKEN

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
  - sonar-scanner
