#.travis.yml
dist: trusty
sudo: required
language: node_js

node_js:
  - 10.15.3

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "wlucha"
    token:
      secure: "5z8ERVwPQ1/kf6jXrhakfAG/nN4x/5Pk4FygNXfBY9lm12eQG8oT196n7nK1XQUYxb4Vei/BnG7jI0SiAssYfLxp+Ut6kind2QDlWNSwyEiP7ep12z8lVkL0yPu90nHHV02omawPoJ62UX6G8crKBwsrFQC1zh469TlncQffwFhbkl57T716v1bcYI0VTmlzLAhSI7M6CVvRm+dg9bR1aH7l/5xnrWGkOVKEDTpUmEmPDMppactevb8KC9yd9F+gek+2hB6ArKavMDL+VxYvLv67pg/llmDzOHo4ZToXVwlrOkv96dRaP19YNyPWhiz8i5ZencQOJlEffZzB/pDcWDVEE02yJxqsEY3ANjWbXSBsYxzYRktgQSlXYwQ2tjpY+e1Q2cuXyzfxSNXrYS1bSFczOlgOi7bfdchL7dnB76cKBA54fWTOt+0bsBWPIo+aiBjs9Mq/TbFqA3/l/vhEWrd1cQp4HVbRmWsBFDhSMJ/wsm0CGQkdw2tBhpVSuqOxQ50pE8QDQ0WFB8prneciruv04yf03q4IfJyCYhFx2TUFKaGuvbqGeUyhO8vFKRrunro0J8iiOh8UkWWCdJJ9/Gg4bXy7R2rgrtv8S3kYRUCqS+BuImz9N1AQc4pdfk2b8z8EXnQ9zfS+iJ+ouZJGBrCsaKoUSODqJZrAcB6jBkY="


install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build
  - sonar-scanner
